### ISSUE TITLE
Why is there SVG flags wich the content is just a filename?

### ISSUE THREAD

**Issue by foxypiratecove37350** [googlefonts/noto-emoji#459]
There is some SVG waved flags which the content is just a filename, like the file `emoji_u1f1e7_1f1fb.svg`:
```xml
emoji_u1f1f3_1f1f4.svg
```

I know this is for flags aliases but it just don't work and do this error during the build for COLRv1 (exemple with the file `emoji_u1f1e8_1f1f5.svg`:
```sh
FAILED: picosvg/clipped/emoji_u1f1e8_1f1f5.svg
picosvg  --clip_to_viewbox --output_file picosvg/clipped/emoji_u1f1e8_1f1f5.svg ../../third_party/region-flags/waved-svg/emoji_u1f1e8_1f1f5.svg
Traceback (most recent call last):
  File "/mnt/c/Dcmt/noto-emoji/venv/bin/picosvg", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/picosvg/picosvg.py", line 76, in main
    app.run(_run, argv=argv)
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/picosvg/picosvg.py", line 53, in _run
    svg = SVG.parse(input_file)
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/picosvg/svg.py", line 1445, in parse
    return cls.fromstring(raw_svg)
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/picosvg/svg.py", line 1434, in fromstring
    tree = etree.fromstring(string.encode("utf-8"), parser)
  File "src/lxml/etree.pyx", line 3264, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1989, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1164, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 672, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
[7252/7683] /mnt/c/Dcmt/noto-emoji/venv/bin/python3 -m nanoemoji.write_p...ped/emoji_u1f1e7_1f1f9.parts.json picosvg/clipped/emoji_u1f1e7_1f1f9.svg
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/mnt/c/Dcmt/noto-emoji/venv/bin/nanoemoji", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/nanoemoji/nanoemoji.py", line 761, in main
    app.run(_run)
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/nanoemoji/nanoemoji.py", line 756, in _run
    maybe_run_ninja(build_file)
  File "/mnt/c/Dcmt/noto-emoji/venv/lib/python3.10/site-packages/nanoemoji/ninja.py", line 125, in maybe_run_ninja
    subprocess.run(ninja_cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-C', '/mnt/c/Dcmt/noto-emoji/colrv1/build']' returned non-zero exit status 1.
```

**Comment by anthrotype** [comment]
I think those are symbolic links.

**Comment by foxypiratecove37350** [comment]
> I think those are symbolic links.

Me, I think those are suposed to be symbolic links but it's just the filename in the SVG file. On my local clone of the repo I've just replaced those by the content of the file with this filename.

**Comment by foxypiratecove37350** [comment]
Nvm I understood, it's Linux symlinks but I was on Windows
